# Generated by Django 3.1.2 on 2020-11-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
