# Generated by Django 3.1.2 on 2020-11-01 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0002_auto_20201101_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=20)),
                ('square', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('lighting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zookeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('experience', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='kind_animal',
            name='diet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kind_animal',
            name='habitat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kind_animal',
            name='lifespan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kind_animal',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kind_animal',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Zoo', to='Zoo.place'),
        ),
        migrations.AddField(
            model_name='animal',
            name='zookeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Zoo', to='Zoo.zookeeper'),
        ),
    ]
