# Generated by Django 3.1.2 on 2020-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0003_auto_20201101_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kind_animal',
            old_name='habitat',
            new_name='character',
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kind_animal',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='kind_animal',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='square',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='place',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='place',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='gender',
            field=models.CharField(choices=[('МУЖ', 'Мужчина'), ('ЖЕН', 'Женщина')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
