# Generated by Django 3.1.2 on 2020-11-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0005_auto_20201101_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='update_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
