# Generated by Django 3.1.2 on 2020-11-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0006_auto_20201101_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind_animal',
            name='update_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='update_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='update_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
