# Generated by Django 3.1.2 on 2020-11-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0007_auto_20201101_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='zookeeper',
            name='animals',
            field=models.ManyToManyField(related_name='_zookeeper_animals_+', to='Zoo.Zookeeper'),
        ),
    ]
