# Generated by Django 3.1.2 on 2020-11-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0008_zookeeper_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='zookeeper',
        ),
        migrations.AddField(
            model_name='animal',
            name='zookeeper',
            field=models.ManyToManyField(to='Zoo.Zookeeper'),
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='animals',
            field=models.ManyToManyField(to='Zoo.Zookeeper'),
        ),
    ]
