# Generated by Django 3.1.2 on 2020-11-01 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0009_auto_20201101_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zookeeper',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='zookeeper',
        ),
        migrations.AddField(
            model_name='animal',
            name='zookeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Zoo', to='Zoo.zookeeper'),
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='experience',
            field=models.DateField(),
        ),
    ]
