# Generated by Django 3.1.2 on 2020-11-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0010_auto_20201101_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zookeeper',
            name='experience',
            field=models.DateTimeField(),
        ),
    ]
